name: Clear Unposted Messages

on:
  # Manual trigger only - this is a destructive operation
  workflow_dispatch:
    inputs:
      clear_all:
        description: 'Clear ALL messages including posted ones (dangerous!)'
        required: false
        type: boolean
        default: false
      confirm:
        description: 'Type "CONFIRM" to proceed'
        required: true
        type: string

jobs:
  clear-database:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    
    steps:
    - name: Validate confirmation
      run: |
        if [ "${{ github.event.inputs.confirm }}" != "CONFIRM" ]; then
          echo "❌ Confirmation not provided. Operation cancelled."
          echo "Please type CONFIRM in the confirm field to proceed."
          exit 1
        fi
        echo "✓ Confirmation received"
    
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create data directory
      run: mkdir -p data
    
    - name: Get latest successful run id (fetch-posts)
      id: get_run_fetch
      uses: actions/github-script@v7
      with:
        script: |
          const runs = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'fetch-posts.yml',
            branch: 'main',
            per_page: 20,
            status: 'success'
          });
          const run = runs.data.workflow_runs && runs.data.workflow_runs[0];
          core.setOutput('run_id', run ? String(run.id) : '');

    - name: Download database from fetch-posts using GitHub CLI
      if: steps.get_run_fetch.outputs.run_id != ''
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        echo "Downloading database from run ${{ steps.get_run_fetch.outputs.run_id }}"
        gh run download ${{ steps.get_run_fetch.outputs.run_id }} --name posts-database --dir data/ || echo "posts-database not found"
      continue-on-error: true
    
    - name: Show database status before clearing
      env:
        BLOG_RSS_FEED_URL: ${{ secrets.BLOG_RSS_FEED_URL }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        DATABASE_PATH: ./data/posts.db
      run: |
        echo "=== Database Status BEFORE Clearing ==="
        python main.py --status
    
    - name: Clear unposted messages
      if: ${{ github.event.inputs.clear_all != 'true' }}
      env:
        DATABASE_PATH: ./data/posts.db
      run: |
        echo "🗑️  Clearing UNPOSTED messages only..."
        python clear_unposted.py
    
    - name: Clear ALL messages (including posted)
      if: ${{ github.event.inputs.clear_all == 'true' }}
      env:
        DATABASE_PATH: ./data/posts.db
      run: |
        echo "⚠️  WARNING: Clearing ALL messages including posted ones!"
        python clear_unposted.py --all << EOF
        yes
        EOF
    
    - name: Show database status after clearing
      env:
        BLOG_RSS_FEED_URL: ${{ secrets.BLOG_RSS_FEED_URL }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        DATABASE_PATH: ./data/posts.db
      run: |
        echo ""
        echo "=== Database Status AFTER Clearing ==="
        python main.py --status
    
    - name: Upload updated database as artifact
      uses: actions/upload-artifact@v4
      with:
        name: posts-database
        path: data/posts.db
        retention-days: 90
    
    - name: Summary
      run: |
        echo ""
        echo "✓ Clear operation complete!"
        echo ""
        if [ "${{ github.event.inputs.clear_all }}" == "true" ]; then
          echo "  Mode: Cleared ALL messages (including posted)"
        else
          echo "  Mode: Cleared UNPOSTED messages only"
        fi
        echo ""
        echo "Next steps:"
        echo "  1. Run 'Fetch New Blog Posts' workflow to reload content"
        echo "  2. Messages will be scheduled automatically"
        echo ""

