name: Test X Posting (Real Blog Content)

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  test-x-post-real:
    name: Test X Post with Real Blog Content + AI Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create data directory
      run: |
        mkdir -p data
    
    - name: Fix database schema (if database exists)
      run: |
        python fix_database_schema.py
      continue-on-error: true
    
    - name: Run real-world X posting test
      env:
        BLOG_RSS_FEED_URL: ${{ secrets.BLOG_RSS_FEED_URL }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
        GENERATE_IMAGES: ${{ vars.GENERATE_IMAGES || '1.0' }}
        X_API_KEY: ${{ secrets.X_API_KEY }}
        X_API_SECRET: ${{ secrets.X_API_SECRET }}
        X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
        X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
        X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
      run: |
        echo "🧪 Starting real-world X posting test..."
        echo ""
        echo "This will:"
        echo "  1. Fetch latest blog post from your RSS feed"
        echo "  2. Extract ONE message with Claude"
        echo "  3. Generate an AI image with Grok"
        echo "  4. Save temporarily to database"
        echo "  5. Post to X (Twitter) with image"
        echo "  6. Clean up database (remove test data)"
        echo ""
        echo "⚠️  WARNING: This will create a REAL tweet on your X account!"
        echo ""
        python test_x_post_real.py
    
    - name: Test summary
      if: always()
      run: |
        if [ $? -eq 0 ]; then
          echo "✅ Real-world X posting test completed successfully!"
          echo "Check your X account to see the post."
        else
          echo "❌ Real-world X posting test failed. Check the logs above."
        fi

